name: Jakarta Contexts and Dependency Injection CI

on:
  push:
    branches-ignore:
      - 'wip/**'
      - 'draft/**'
    paths-ignore:
      - '.gitignore'
      - 'CONTRIBUTING.adoc'
      - 'NOTICE.md'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '.gitignore'
      - 'CONTRIBUTING.adoc'
      - 'NOTICE.md'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
  workflow_dispatch:

jobs:
  build:
    name: "Build CDI - JDK ${{matrix.java}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: "Maven install"
        run: |
          mvn -Pstaging install -DskipTests=true -B -V
      - name: "Maven test"
        run: |
          mvn -Pstaging test -B
